### ISSUE TITLE
[k8s] alpine containers are killed per 30 seconds; ubuntu/debian are killed immediately

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/usernetes#10]

**Comment by AkihiroSuda** [comment]
@giuseppe 
Probably this is dockershim-specific.
Do you hit this issue with cri-o?

**Comment by giuseppe** [comment]
yes, I've seen the same issue with CRI-O and I thought it was specific to CRI-O.

**Comment by giuseppe** [comment]
the container gets immediately a SIGTERM, I had to use the spec file from here to get the container running: https://github.com/rootless-containers/usernetes/issues/11#issuecomment-412953227
