### ISSUE TITLE
kube-proxy proxy-mode

### ISSUE THREAD

**Issue by liaohang122** [rootless-containers/usernetes#185]
usernetes/boot/kube-proxy.sh  
proxy-mode can iptables or ipvs be supported ？

**Comment by AkihiroSuda** [comment]
Haven't tried

**Comment by liaohang122** [comment]
iptables mode is ok

**Comment by AkihiroSuda** [comment]
ipvs doesn't work?

**Comment by AkihiroSuda** [comment]
https://github.com/kubernetes/kubernetes/issues/103860

Userspace proxy is being removed, so we have to switch to iptables
