### ISSUE TITLE
Cannot make HTTP requests to kube-apiserver from inside cluster when 6443 is not published

### ISSUE THREAD

**Issue by maybe-sybr** [rootless-containers/usernetes#216]
As part of some further experimentation, I've been trying to deploy multiple usernetes on the same machine and setting up different high ports to publish the kube-apiserver to things outside of the cluster. The setup is basically:

```
$ HIGH_PORT=$(( $RANDOM + 1024))
$ ./install.sh --cri=crio --publish="127.0.0.1:${HIGH_PORT}:6443/tcp"
$ sed -i "s/:6443/:${HIGH_PORT}/" ~/.config/usernetes/master/admin-*.kubeconfig
```

I can make a request to the kube-apiserver from outside rootlesskit like so:
```
$ curl -k https://localhost:17488
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
$ kubectl --kubeconfig ~/.config/usernetes/master/admin-localhost.kubeconfig version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-07-28T00:00:00Z", GoVersion:"go1.15rc1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-beta.0", GitCommit:"66fa2c49e28b9dcf478a87636971bc7d241b2849", GitTreeState:"clean", BuildDate:"2021-02-23T20:30:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

However when I attempt to make a similar request to the in-cluster end of the API server, I get my connection reset:
```
$ ./rootlessctl.sh list-ports
ID    PROTO    PARENTIP     PARENTPORT    CHILDPORT
1     tcp      127.0.0.1    17488         6443
$ kubectl run --rm -ti --restart=Never --image docker.io/library/busybox:stable foo -- wget https://10.0.0.1
Connecting to 10.0.0.1 (10.0.0.1:443)
wget: note: TLS certificate validation not implemented
wget: got bad TLS record (len:0) while expecting handshake record
wget: error getting response: Connection reset by peer
pod "foo" deleted
pod default/foo terminated (Error)
```

This manifests in breakage in the coredns manifests bundled with usernetes since they can't access the api server and then fail their readiness checks.
```
Events:
  Type     Reason     Age                From                             Message
  ----     ------     ----               ----                             -------
  Normal   Scheduled  <unknown>                                           Successfully assigned kube-system/coredns-76f5d77d78-twrvj to virt-test.lan
  Warning  BackOff    22s (x4 over 66s)  kubelet, virt-test.lan  Back-off restarting failed container
  Normal   Pulled     8s (x4 over 107s)  kubelet, virt-test.lan  Container image "coredns/coredns:1.8.3" already present on machine
  Normal   Created    8s (x4 over 107s)  kubelet, virt-test.lan  Created container coredns
  Normal   Started    8s (x4 over 107s)  kubelet, virt-test.lan  Started container coredns
  Warning  Unhealthy  4s (x7 over 104s)  kubelet, virt-test.lan  Readiness probe failed: Get "http://10.88.0.36:8181/ready": dial tcp 10.88.0.36:8181: connect: connection refused
```

Adding the default `0.0.0.0:6443:6443/tcp" port forward makes everything work as normal, but then multiple usernetes cannot co-exist on the same machine and it seems likely that there will be cross-talk between the clusters since packets are obviously making their way outside of the cluster somehow! Interestingly, adding a `127.0.0.1:6443:6443/tcp` *does not* fix the misbehaviour. For context in the shell output below, 10.255.255.1 is an IP on a dummy interface on my box - effectively localhost. Note that only the `0.0.0.0:6443` rule works (ie. allows me to request the API server and get a 401 response).

```
$ ./rootlessctl.sh add-ports 0.0.0.0:6443:6443/tcp
2
$ kubectl run --rm -ti --restart=Never --image docker.io/library/busybox:stable foo -- wget https://10.0.0.1
Connecting to 10.0.0.1 (10.0.0.1:443)
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 401 Unauthorized
pod "foo" deleted
pod default/foo terminated (Error)
(failed reverse-i-search)`remove': kubectl run --rm -ti --^Cstart=Never --image docker.io/library/busybox:stable foo -- wget https://10.0.0.1
$ ./rootlessctl.sh remove-ports 2
2
$ ./rootlessctl.sh add-ports 127.0.0.1:6443:6443/tcp
3
$ kubectl run --rm -ti --restart=Never --image docker.io/library/busybox:stable foo -- wget https://10.0.0.1
Connecting to 10.0.0.1 (10.0.0.1:443)
wget: note: TLS certificate validation not implemented
wget: short read, have only 0: Connection reset by peer
wget: error getting response: Connection reset by peer
pod "foo" deleted
pod default/foo terminated (Error)
$ kubectl delete^Cod foo
$ ./rootlessctl.sh remove-ports 3
3
$ ./rootlessctl.sh add-ports 10.255.255.1:6443:6443/tcp
4
$ kubectl run --rm -ti --restart=Never --image docker.io/library/busybox:stable foo -- wget https://10.0.0.1
Connecting to 10.0.0.1 (10.0.0.1:443)
wget: note: TLS certificate validation not implemented
wget: short read, have only 0: Connection reset by peer
wget: error getting response: Connection reset by peer
pod "foo" deleted
pod default/foo terminated (Error)
```

This can be fixed by configuring the coredns deployment to point at the rootlesskit tap's IP using one of the two following patch hunks:
```diff
diff --git a/manifests/coredns.yaml b/manifests/coredns.yaml
index e39d3f9..93446ff 100644
--- a/manifests/coredns.yaml
+++ b/manifests/coredns.yaml
@@ -58,6 +58,7 @@ data:
         health
         ready
         kubernetes cluster.local in-addr.arpa ip6.arpa {
+          endpoint https://10.0.42.100:6443
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
         }
@@ -109,6 +110,11 @@ spec:
             cpu: 100m
             memory: 70Mi
         args: [ "-conf", "/etc/coredns/Corefile" ]
+        env:
+        - name: KUBERNETES_SERVICE_HOST
+          value: "10.0.42.100"
+        - name: KUBERNETES_SERVICE_PORT
+          value: "6443"
         volumeMounts:
         - name: config-volume
           mountPath: /etc/coredns
```
and adding the tap's IP to the cert generation with this patch:
```diff
diff --git a/common/cfssl.sh b/common/cfssl.sh
index ae30d95..3e0a5dc 100755
--- a/common/cfssl.sh
+++ b/common/cfssl.sh
@@ -141,7 +141,7 @@ else
 	log::info "Creating ${master_d}/{kubernetes.pem,kubernetes-key.pem}"
 	k_hostnames="kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
 	ip_addrs=$(hostname -I | sed -e 's/ /,/g' -e 's/,$//g')
-	k_cluster_ip="10.0.0.1"
+	k_cluster_ip="10.0.42.100,10.0.0.1"
 	cfssl gencert -loglevel="$loglevel" \
 		-ca="${master_d}/ca.pem" \
 		-ca-key="${master_d}/ca-key.pem" \
```
But obviously that would need to be fed the value of `--cidr` from `install.sh` to be correct.

However, fixing each instance of this breakage seems like it'll just be a game of whack-a-mole and it would be better for in-cluster access to the API sevice to Just Work (TM).

My best theory is that kube-proxy is directing the traffic to `<host_ip>:6443` which allows the packet to escape the network namespace and then only be able to get back in via the rootlesskit port forward. It's a bit hard to tell with the userspace kube-proxy driver.

**Comment by maybe-sybr** [comment]
Actually, I just tried the `iptables` driver for kube-proxy and it's a bit more clear what is happening here. The following rule is being used to redirect in-cluster traffic to the API server:

```
$ nsenter -U -r -n -m -t $(cat /run/user/1000/usernetes/rootlesskit/child_pid) iptables -nvL -t nat
...
Chain KUBE-SEP-OGNOLD2JUSLFPOMZ (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 KUBE-MARK-MASQ  all  --  *      *       10.0.2.15            0.0.0.0/0            /* default/kubernetes:https */
    5   300 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ tcp to:10.0.2.15:6443
```

As you can see, a few packets have hit the DNAT rule which are from me running the same `busybox wget ...` pod from above.

This rule should probably be pointing to the address of the rootlesskit tap, or perhaps 127.0.0.1 would even work... I'd have to experiment a bit to see if the DNAT rule actually functions okay as a PAT to localhost.

**Comment by maybe-sybr** [comment]
So I think this comes down to the same issue I raised back in October of last year (#193) where a machine with no configured host IP couldn't run usernetes at all because the scripts assume one is present. It's a different manifestation but I suspect fixing it will be similarly annoying because it's obvious that making the kube-apiserver advertise an IP internal to the rootlesskit netns  will make the single usernetes node case work. However, I have no idea if this will break things with a multi-node cluster as you described in that issue.

I would suggest this patch:
```patch
From e65909383eb36ae2f81131b3260395e6af3098df Mon Sep 17 00:00:00 2001
From: maybe-sybr <58414429+maybe-sybr@users.noreply.github.com>
Date: Wed, 10 Mar 2021 13:57:47 +1100
Subject: [PATCH] fix: Make k8s API advertise the rootlesskit IP

This change ensures that the `kube-apiserver` is configured to advertise
its endpoint using an IP from within the rootlesskit network namespace.
This ensures that traffic from within the cluster is redirected by
`kube-proxy` within the rootlesskit namespace rather than out to the
host and relying on rootlesskit port forwarding to send it back in.
---
 boot/kube-apiserver.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/boot/kube-apiserver.sh b/boot/kube-apiserver.sh
index ed421ee..a5c990c 100755
--- a/boot/kube-apiserver.sh
+++ b/boot/kube-apiserver.sh
@@ -17,7 +17,7 @@ exec $(dirname $0)/nsenter.sh kube-apiserver \
 	--service-cluster-ip-range=10.0.0.0/24 \
 	--service-account-issuer="kubernetes.default.svc" \
 	--service-account-signing-key-file=$XDG_CONFIG_HOME/usernetes/master/service-account-key.pem \
-	--advertise-address=$(cat $XDG_RUNTIME_DIR/usernetes/parent_ip) \
+	--advertise-address=$(nsenter::_nsenter hostname -I | cut -d ' ' -f 1) \
 	--allow-privileged \
 	$@
 
-- 
2.29.2
```

But while it will fix things for me, I'd guess it'll cause issues with flannel? Is there a way we could make it advertise either a flannel IP or the rootlesskit's slirp IP, but never the parent IP? Are there other deployment environments where not using the parent IP would break cross-node communications?

**Comment by AkihiroSuda** [comment]
Thanks, I *think* your patch above works with Flannel as long as the port is published via RootlessKit.

**Comment by maybe-sybr** [comment]
If that's the case, I can make a PR and mark it as closing both this issue and #193 since there'll no longer be a problem with the apiserver not having a value for `--advertise-address` if we're always setting it to an address from inside the netns.

We may need to come up with a way to prefer the address on slirp tap interfaces or whatever flannel sets up. It would be a problem if we accidentally selected some odd address which couldn't be reached across the flannel internetwork. Perhaps we should be using something like `ip addr show dev <name>` instead?

**Comment by AkihiroSuda** [comment]
Let me close this, as the architecture was changed in "Generation 2":
https://github.com/rootless-containers/usernetes/releases/tag/gen2-v20230906.0
