### ISSUE TITLE
"Failed to connect to bus: No such file or directory" attempting to run usernetes in docker

### ISSUE THREAD

**Issue by mallman** [rootless-containers/usernetes#226]
Hello.

I'm following the instructions for running usernetes in a docker container using the command

```sh
docker run -td --name usernetes-node -p 127.0.0.1:6443:6443 --privileged rootlesscontainers/usernetes --cri=containerd
```

I've tried running this in three docker environments:

1. Docker 20.10.6 on macOS Big Sur
2. Docker 19.03.13 on Ubuntu 18.04 multipass on macOS Big Sur
3. Docker 20.10.4 on CentOS 7 on a GCE instance

In every case the container exits very quickly after launch with the error

```
Failed to connect to bus: No such file or directory
```

**Comment by AkihiroSuda** [comment]
Docker Hub image might be broken, could you try rebuilding the image from Dockerfile? (with DOCKER_BUILDKIT=1)

**Comment by mallman** [comment]
I tried rebuilding the image and I got the same error running it.

**Comment by AkihiroSuda** [comment]
I confirmed that I can repro this issue on my machine as well, but not on CI... https://github.com/rootless-containers/usernetes/pull/227/checks?check_run_id=2627297795 
🤔

**Comment by mallman** [comment]
🤔 indeed...

**Comment by Diliz** [comment]
Got the same issue on wsl2, did you found why it's doing this?

**Comment by AkihiroSuda** [comment]
Please try the latest version. The architecture has changed significantly.
