### ISSUE TITLE
controller `cpu` is not available - usernetes:latest cgroups v1

### ISSUE THREAD

**Issue by dg424** [rootless-containers/usernetes#241]
I'm getting the following error:

kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: the requested cgroup controller `cpu` is not available: unknown

I see here - https://github.com/rootless-containers/usernetes#enable-cpu-controller - that it seems related to cgroups v2, but I'm using the "latest" which should still be cgroups v1 as per this - https://github.com/rootless-containers/usernetes/issues/239#issuecomment-907186653 ?

**Comment by AkihiroSuda** [comment]
Let me close this, as cgroup v1 is no longer supported
