### ISSUE TITLE
Problem when cri-o is already installed on the system

### ISSUE THREAD

**Issue by lucabe72** [rootless-containers/usernetes#253]
Hi all,

I tried the latest usernetes release, and I had problems starting it. After some investigation, it turned out that the "u7s-rootlesskit" service failed to start, because crio complained "open /var/lib/crio/.version424976977: permission denied".
I think this happened because my test system already had cri-o installed, so the /var/lib/crio directory already exists, and the "--copy-up /var/lib" option passed to rootlesskit created a symbolic link to such a directory... So, the usernetes' cri-o was not able to write there.

After removing /var/lib/crio from my system, usernetes started regularly.

Is this a known issue, am I doing something wrong (maybe I misconfigured something?), or something else?

Thanks,
Luca

**Comment by AkihiroSuda** [comment]
Probably we have to add `/var/lib/crio` to this line
https://github.com/rootless-containers/usernetes/blob/f39f23d4a248b7c1a42839ffc891afcb0a50bd17/boot/rootlesskit.sh#L77

**Comment by lucabe72** [comment]
On Fri, 21 Jan 2022 at 08:19, Akihiro Suda ***@***.***> wrote:

> Probably we have to add /var/lib/crio to this line
>
> https://github.com/rootless-containers/usernetes/blob/f39f23d4a248b7c1a42839ffc891afcb0a50bd17/boot/rootlesskit.sh#L77
>

This worked perfectly, thank you very much!
Problem solved :)


Luca
