### ISSUE TITLE
Multinode kubernetes cluster setup on different hosts

### ISSUE THREAD

**Issue by cloud-66** [rootless-containers/usernetes#262]
Hello, thank you for big work done.
I installed single node cluster by install.sh   script
Also tried multinode setup by docker-compose up.
But there is no instuction how to run Multinode  cluster on different hosts.
It probably needs to be done at the moment in the "hard way" style.
But also it's hard to understand how the network should work.
Of course It takes a lot of time  to create  complete instruction or automation of installation.
Is it possible to create common  not necessarily detail instruction how to do that?

**Comment by AkihiroSuda** [comment]
No documentation/script for multi-node setup yet, please replicate the process in the docker-compose.yaml.

Eventually we should support kubeadm though.

**Comment by cloud-66** [comment]
Thank you. Does it means that the goal is to implement rootless installation in original kubeadm by options? Or it will be some fork of kubeadm.

**Comment by danfulton** [comment]
@AkihiroSuda I've also been trying to do this recently, and struggling to get traction.  I'd be happy to make contributions to either documentation or a kubeadm port, but would very much appreciate if you have any pointers.

**Comment by cheungsuifai** [comment]
> Hello, thank you for big work done. I installed single node cluster by install.sh script Also tried multinode setup by docker-compose up. But there is no instuction how to run Multinode cluster on different hosts. It probably needs to be done at the moment in the "hard way" style. But also it's hard to understand how the network should work. Of course It takes a lot of time to create complete instruction or automation of installation. Is it possible to create common not necessarily detail instruction how to do that?

FYI:
#275

**Comment by AkihiroSuda** [comment]
Please try this:
- https://github.com/rootless-containers/usernetes/pull/287
