### ISSUE TITLE
u7s upgrade  (kubeadm)

### ISSUE THREAD

**Issue by cheungsuifai** [rootless-containers/usernetes#270]
Within k8s, the cluster is upgrade with the kubeadm command.

But the cluster is deployed via "hard way" in u7s, and kubeadm is excluded in the release.

So is the only way to upgrade u7s cluster to **undeploy-redeploy with the newer version** ?
Is there any plan for **introducing kuebadm** and **providing a easier upgrade method**?

**Comment by AkihiroSuda** [comment]
Help wanted to support kubeadm.

**Comment by AkihiroSuda** [comment]
Duplicate of
- #69
