### ISSUE TITLE
nvidia GPU not support due to cgroup mountpoint not found

### ISSUE THREAD

**Issue by cheungsuifai** [rootless-containers/usernetes#274]
I planned to test the GPU availability on u7s.
Due to my GPU device is Nvidia Tesla T4, I tried to deploy the nvidia device plugin daemonset.
For this, I switched the containerd runtime from origin crun to nvidia's (**v1.13**).
```
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
```

But after that, the Pod failed to start with the below log:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: container_[linux.go:348](http://linux.go:348/): starting container process caused "process_[linux.go:279](http://linux.go:279/): applying cgroup configuration for process caused \"mountpoint for cgroup not found\"": unknown
```

I guessed the reason is after cgroup v2  enabled, there was no `/sys/fs/cgroup/devices` mounted.

So I set `no-cgroups = true` in `/etc/nvidia-container-runtime/config.toml` .

But **"mountpoint for cgroup not found"** problem still there.

**Comment by AkihiroSuda** [comment]
I think you should report this to https://github.com/NVIDIA/nvidia-container-runtime

**Comment by cheungsuifai** [comment]
> I think you should report this to https://github.com/NVIDIA/nvidia-container-runtime

Sorry to raise the issue here.
But actually I have gone through the issue of
