### ISSUE TITLE
services don't start after reboot node automatically

### ISSUE THREAD

**Issue by cloud-66** [rootless-containers/usernetes#278]
I installed  rootless cluster on 3 master\worker   + 2 worker nodes

![image](https://user-images.githubusercontent.com/41143306/231204114-08c59c59-425e-43d7-b2a9-c12980aff122.png)
sudo loginctl enable-linger
enabled
![image](https://user-images.githubusercontent.com/41143306/231204971-b505a4eb-366f-45d8-95a3-729e1397de2d.png)

systemctl list-unit-files --user
manually tried to enable services
before
![image](https://user-images.githubusercontent.com/41143306/231205555-c3a42e90-a2d5-4262-8358-8de12c2958dc.png)

after
![image](https://user-images.githubusercontent.com/41143306/231205304-4d96f1d9-874d-48ab-93dd-fc2aade1f07c.png)

But still, services don't start after reboot node by ```shutdown -r now```
Is this a feature of installation or some mistake in configuration ?

I'm going to use this kind of cluster in production. And of course it is much better to keep working after reboot without manual starting kubernetes components

**Comment by AkihiroSuda** [comment]
Addressed in #279
