### ISSUE TITLE
Remove `ip addr add "${U7S_HOST_IP}" dev eth0`

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/usernetes#296]
https://github.com/rootless-containers/usernetes/blob/9c454e1bf8dc81d18a49ad0bdf932fec08944e90/Dockerfile.d/u7s-entrypoint.sh#L7-L9

It is weird to assign the host IP to the eth0 of the node container.

Depends on:
- https://github.com/kubernetes/kubernetes/issues/54337

**Comment by aojea** [comment]
do you want to configure the externalIP of the node?

**Comment by aojea** [comment]
if you start the kubelet with cloud-provider external you can update the status of the node object and it will pick those addresses, now you can do it with kubectl `kubectl patch node --type=merge --subresource status --patch '.....'`

**Comment by AkihiroSuda** [comment]
> if you start the kubelet with cloud-provider external you can update the status of the node object and it will pick those addresses, now you can do it with kubectl `kubectl patch node --type=merge --subresource status --patch '.....'`

Thanks, but ClusterIPs such as 10.96.0.1 are still inaccessible from worker nodes.
Is there any additional step needed to configure kube-proxy (?) or something?

**Comment by AkihiroSuda** [comment]
Thanks @aojea , implemented your suggestion in https://github.com/rootless-containers/usernetes/releases/tag/gen2-v20240404.1 (#323)
