### ISSUE TITLE
[crio] does not work when /etc/containers/policy.json is unavailable on the host

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/usernetes#30]
```
[kubelet-crio] E0824 07:42:07.848387   13836 pod_workers.go:186] Error syncing pod f2bae4d7-a770-11e8-8182-7a7eddbf465f ("foo-7b675c6d5-trfmv_default(f2bae4d7-a770-11e8-8182-7a7eddbf465f)"), skipping: failed to "CreatePodSandbox" for "foo-7b675c6d5-trfmv_default(f2bae4d7-a770-11e8-8182-7a7eddbf465f)" with CreatePodSandboxError: "CreatePodSandbox for pod \"foo-7b675c6d5-trfmv_default(f2bae4d7-a770-11e8-8182-7a7eddbf465f)\" failed: rpc error: code = Unknown desc = error creating pod sandbox with name \"k8s_foo-7b675c6d5-trfmv_default_f2bae4d7-a770-11e8-8182-7a7eddbf465f_0\": open /etc/containers/policy.json: no such file or directory"
```

**Comment by AkihiroSuda** [comment]
workaround #31: create `~/.local/share/usernetes/_etc_containers/policy.json` on the first boot and bind-mount `~/.local/share/usernetes/_etc_containers/` on `/etc/containers`

@giuseppe @rhatdan

Could you modify rootless crio (and podman/skopeo perhaps) to use `~/.config/containers` instead of `/etc/containers`?
Also, it would be great if crio can generate default `policy.json` automatically.

**Comment by giuseppe** [comment]
I've opened a patch for podman: https://github.com/containers/libpod/pull/1336

Going to take a look at the CRI-O side now

**Comment by AkihiroSuda** [comment]
thanks!

**Comment by giuseppe** [comment]
@AkihiroSuda should be enough to override this setting `crio --signature-policy=.. ` What do you think?

**Comment by AkihiroSuda** [comment]
Yes, probably it is ok for now

**Comment by giuseppe** [comment]
I'll prepare a PR soon
