### ISSUE TITLE
Testing on ARM

### ISSUE THREAD

**Issue by vsoch** [rootless-containers/usernetes#321]
I'm building a node for arm, and I noticed the Dockerfile is hard coded to a sha, which I would suspect is for AMD64. I am wondering if it would make sense to remove the sha pin and allow for the platform to be selected instead? What I'm doing now is trying out an arm sha and can report back. It does look like the rest of the Dockerfile is going to account for arm (e.g., CNI plugins). I suspect there might be more issues though.

**Comment by vsoch** [comment]
We're in business! :partying_face: 
![image](https://github.com/rootless-containers/usernetes/assets/814322/8a3c50d9-58f6-4ffc-bad4-4b9c84f29b84)

I used this digest.
```dockerfile
ARG BASE_IMAGE=docker.io/kindest/node:v1.29.1@sha256:b106f306d3728848d91c79929005c6295f3365da713734345c74325abf92139f
```

No other issues so far.

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/usernetes/blob/a0ce8e378dc821500a47e831229ae3b172a7f16d/Dockerfile#L1

The default digest should work on arm64 too
https://explore.ggcr.dev/?image=docker.io%2Fkindest%2Fnode%3Av1.29.1%40sha256%3Aa0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144

**Comment by vsoch** [comment]
Ah ok! I should have just tried it instead of thinking too hard about it. Thanks!
