### ISSUE TITLE
`systemctl --user` (allow to restart a single service)

### ISSUE THREAD

**Issue by giuseppe** [rootless-containers/usernetes#33]
we are currently running each service (etcd, k8s services, runtime) as part of a `Taskfile.yml`.

It'd be nice if we support restarting a single service, perhaps not using `go-task` for handling the bootstrap of Usernetes.

Perhaps `systemctl --user`?

The biggest problem I see is that all the services must be in the same user namespace

**Comment by AkihiroSuda** [comment]
> Perhaps systemctl --user?
> The biggest problem I see is that all the services must be in the same user namespace

Probably we should launch "pause" service via rootlesskit first, and then start other services via nsenter.

**Comment by AkihiroSuda** [comment]
@giuseppe 

I'm going to adopt `systemd --user`.

While I do want to support non-systemd system (especially Usernetes-in-Docker), but I don't want to maintain both `Taskfile.yml` and systemd unit files...

Is there way to execute systemd unit files without actual systemd running?

**Comment by AkihiroSuda** [comment]
Also we would need to determine the binary path (`~/bin`? `~/opt/usernetes/bin`? `~/.local/share/usernetes/bin`? `~/.local/bin`?)

**Comment by AkihiroSuda** [comment]
The best way seems to use plain old SysV scripts.

Both systemd and Taskfile should be able to execute SysV scripts.

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/usernetes/pull/62 splits `Taskfile.yml` to a set of plain shell scripts.

Now it should be easy to add `systemctl --user` unit scripts.

**Comment by AkihiroSuda** [comment]
I'm planning to implement this soon using https://github.com/AkihiroSuda/containerized-systemd .
