### ISSUE TITLE
[k8s] /etc/docker/certs.d/k8s.gcr.io: permission denied

### ISSUE THREAD

**Issue by frezbo** [rootless-containers/usernetes#8]
The pods like pause is failing to be pulled:
```
tePodSandbox for pod \"pod1_default(afaf1c4e-9a2d-11e8-b119-ae906b331d15)\" failed: rpc error: code = Unknown desc = failed pulling image \"k8s.gcr.io/pause:3.1\": Error response from daemon: open /etc/docker/certs.d/k8s.gcr.io: permission denied"
```
I was able to manually run containers with the `dockercli.sh` script and  using the vfs driver in fedora.

**Comment by AkihiroSuda** [comment]
Thanks for the report, does `rootlesskit --copy-up=/etc/docker/certs.d ...` work as a workaround?

**Comment by frezbo** [comment]
Yeh that should , I will do extensive testing when I get time and report back.

**Comment by AkihiroSuda** [comment]
did it work for you?

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/usernetes/commit/2cce4807ecc2ffac41c12c6230071505744d1b24#diff-e142e19477347e90cb3a93016eac4c6bR40 should fixed the issue
