### ISSUE TITLE
Not working on OpenVZ

### ISSUE THREAD

**Issue by stevefan1999-personal** [rootless-containers/usernetes#85]
Following the requirements and download steps, I wasn't able to use even dockerd (but actually the fault of rootlesskit) on a OpenVZ container:
```
[root@s usernetes]# ./run.sh default-docker-nokube                                                                                                                                                                                  
./boot/dockerd.sh
./boot/rootlesskit.sh
[rootlesskit] [rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted
task: Failed to run task "rootlesskit": exit status 1
```

uname:
```
[root@s usernetes]# uname -a
Linux s 2.6.32-042stab128.2 #1 SMP Thu Mar 22 10:58:36 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Template: CentOS 7 Minimal

However, `cat /proc/self/exe` does work, and it shows a bunch of garbled characters (well they're assembly anyway)

**Comment by AkihiroSuda** [comment]
Could you try newer kernel

**Comment by stevefan1999-personal** [comment]
@AkihiroSuda Unfortunately, the host denied the upgrade request. I recall OVZ 7 is using 3.10.0 and it support Docker out of the box already.

**Comment by AkihiroSuda** [comment]
Unfortunately kernel 2.6.32 cannot be supported, as it lacks support for user namespaces
