### ISSUE TITLE
kubelet: split CgroupManager as a separate gRPC service? or move to CRI

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/usernetes#96]
If we could separate out [`CgroupManager`](https://github.com/kubernetes/kubernetes/blob/21c9c7a6ab4786fadb4056f0a49f1969acc340db/pkg/kubelet/cm/types.go#L70) to a separate gRPC service that would listen on an UNIX socket, it might be easier to experiment cgroup2 driver as well as "NOP" driver.

@giuseppe WDYT?

cc @ibuildthecloud @cyphar

**Comment by AkihiroSuda** [comment]
or maybe the functionality should be handled in CRI runtime?

**Comment by AkihiroSuda** [comment]
Probably cgroup2 will be only supported via systemd API and, it might not make sense to have a separate gRPC service for kubelet CgroupManager.

But I'm still curious whether the kubelet CgroupManager can be moved to CRI runtimes..

**Comment by giuseppe** [comment]
I am not really familiar with all  the Kubelet does but we already have another issue with it trying to use directly cgroups and stepping on the runtime.  We need someone more experienced with the Kubelet into the discussion, but IMO there should be a cleaner separation between the Kubelet and the runtime.
I must try how it performs with crun on a cgroup v2 unified mode system, I'd expect CRI-O to just work, and see how far the Kubelet goes.

CC @mrunalp

**Comment by AkihiroSuda** [comment]
As discussed in Twitter, maybe fuse-ing cgroupfs is the most straightforward way, though not ideal.
